### ISSUE TITLE
Store values into a {entity}_values table

### ISSUE THREAD

**Issue by IsraelOrtuno** [IsraelOrtuno/Propertier#10]
This could improve performance as every entity would have its own values table. Mostly when having a lot of entities, the current way could really affect performance.

**Comment by IsraelOrtuno** [comment]
cc: @dkulyk 
What do you think about this? This could result a little bit more difficult to handle, but we may result with this tables:

```
company -> company_values
employee -> employee_values
```

This way we can avoid having a crazily big `property_values` table... Maybe we can consider this for future versions.

**Comment by dkulyk** [comment]
Search index will occur quickly, regardless of the number of tables.
You can make an optional functionality, the assignment tables in the model.

``` php
class Entity extends Model {
    use Propertier;
    protected $table_values = 'entity_values'; // property_values by default
}
```

**Comment by IsraelOrtuno** [comment]
True, will leave it in the backlog for now.

El martes, 2 de febrero de 2016, Dmytro Kulyk notifications@github.com
escribió:

> Search index will occur quickly, regardless of the number of tables.
> You can make an optional functionality, the assignment tables in the model.
> class Entity extends Model {
> use Propertier;
> protected $table_values = 'entity_values'; // property_values by default
> }
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/IsraelOrtuno/Propertier/issues/10#issuecomment-178585118
> .

## 

Un saludo
Israel Ortuño
