### ISSUE TITLE
How To add it Eloquent Model?? 

### ISSUE THREAD

**Issue by mikimaine** [IsraelOrtuno/Propertier#12]
where is the documentation ??
at list to start with it ?

**Comment by IsraelOrtuno** [comment]
It's still under development. I am working hard on it these days. It'll be ready very soon.

I would really appreciate some beta testing... Are you interested?

**Comment by mikimaine** [comment]
yes i am ...

**Comment by IsraelOrtuno** [comment]
Will catch you on e-mail when ready, expect very soon. Thanks for interest ;)
