### ISSUE TITLE
Quick search for properties

### ISSUE THREAD

**Issue by dkulyk** [IsraelOrtuno/Propertier#16]
`Entity::query()->where('prpname','value')`
Eloquent scope of such properties and is automatically adds join for properties

``` SQL
SELECT entity.* 
FROM entity 
    JOIN property_values AS eav_prpname 
    ON(entity.id = eav_prpname.entity_id and eav_prpname.property_id = 1) 
WHERE eav_prpname.value = 'value'
```

See https://github.com/dkulyk/eloquent-extra/blob/master/src/DKulyk/Eloquent/Properties/QueryScope.php

**Comment by IsraelOrtuno** [comment]
Will research on this. Can we use relations here instead of playing with the query builder and joins?

**Comment by dkulyk** [comment]
Relationships are not suitable. As they establish a single relation for both models. And we need to use join for each property.

**Comment by IsraelOrtuno** [comment]
It has been implemented :dancer: 

``` php
Product::with('fields')->whereHas('colors', function($query) {
    $query->where('value', 'Purple');
})->get();
```
