### ISSUE TITLE
Deleting values when Soft Deleting the entity

### ISSUE THREAD

**Issue by dkulyk** [IsraelOrtuno/Propertier#22]
Should I remove the value for soft delete?

**Comment by IsraelOrtuno** [comment]
Umm I think for soft deleting values should be kept in place, don't they? We'll have to play with the SoftDeletes trait

**Comment by IsraelOrtuno** [comment]
Just one thing to consider...

If an entity is soft deleted, when querying for searches, values will be persisted and they may point to a soft deleted company. Consider this.

**Comment by dkulyk** [comment]
You can try something like

``` PHP
if (!in_array(SoftDeletes::class, class_uses_recursive(get_class($entity)), true) || $entity->forceDeleting) {
    //delete
}
```

**Comment by IsraelOrtuno** [comment]
Will take that into account :smile:

**Comment by IsraelOrtuno** [comment]
I sent you an email yesterday, do you think we can chat over Skype, Hangouts or some other platform? @dkulyk

**Comment by IsraelOrtuno** [comment]
Done e090aa7e78da4d1da0ac5a705079190b6f416559
