### ISSUE TITLE
error when publishing the package file

### ISSUE THREAD

**Issue by mikimaine** [IsraelOrtuno/Propertier#32]
when running php artisan vendor:publish --provider="Devio\Eavquent\EavquentServiceProvider" command This error pops ? any idea ? it is trying to instantiate the trait inside devio\eavquent\src\Evaquent.php trait.

' PHP Fatal error:  Cannot instantiate trait Devio\Eavquent\Eavquent in C:\wamp\www\ecommerce\vendor\laravel\framework\src\Illuminate\Foundation\ProviderRepository.php on line 146

  [Symfony\Component\Debug\Exception\FatalErrorException]
  Cannot instantiate trait Devio\Eavquent\Eavquent '

**Comment by IsraelOrtuno** [comment]
Gonna have a look right now. Thanks for reporting.

**Comment by mikimaine** [comment]
Actually the problem was on the read me file. the code for  inserting the service provider in  app.php file was like this  
`'providers' => [
    ...
    Devio\Eavquent\Eavquent::class
    ...
]`
should be changed to 
`'providers' => [
    ...
   Devio\Eavquent\EavquentServiceProvider::class
    ...
]`
simple error on your Readme file but you should correct it soon!!
