### ISSUE TITLE
Category for the eva attributes ?? 

### ISSUE THREAD

**Issue by mikimaine** [IsraelOrtuno/Propertier#33]
i was thinking to define some category of attribute for some type of models.

for example if i have a product Model then i'll use the trait and add new attributes.
but if i want those attribute again and again i should put those in the same category.
for Phone Product i might have size,brand,Mpx and other phone related attributes....
and for Cloth Product there is a size,type and other cloth related attribute so what i think is if i can put those Phone related attributes in one category and reuse them later ......

so, related attribute will be in side the same attribute sets(categorys) .

Thanks!

**Comment by IsraelOrtuno** [comment]
That sounds interesting but I would have to think about that. It really breaks the current structure...

It would require 1 query constraint in order to add attributes to those product that match a particular query... Let's say something like:

```
Product::where('category', 'clothing');
```

Things like that right?

**Comment by IsraelOrtuno** [comment]
Just thinking a bit about this... We could add a kind of `constraint` column to the attributes table. That column should contain the constraints added between the attributes and the entity...

The idea may work, but this will break caching a little bit as attributes are cached and never fetched again from database till cache is manually refreshed or a new attribute is added...

Keep thinking...

**Comment by IsraelOrtuno** [comment]
Ok just a bit more of thinking, that may work with the constraint... Will take this really into account, I really think it's a good feature, but I do not think I will be able to implement for a first release... I will consider for v2

**Comment by mikimaine** [comment]
If We add one eav_attribute_set table with only an id and attribute_set_name column then we should also add one column to the eav_attributes table with the foreign_key of the id .... 

Every time a new attribute is add we will associate that id with a specific category to eliminate a repetition of attribute in the eav_attributes table. other ways  there might exist more that one existence of the same attributes and also every time a model save's, a key=>value pair should be given. 

if we can find any way to implement this in the current version that will make it solid for production i guess .... with some refactoring ....
