### ISSUE TITLE
Is there a timeline?

### ISSUE THREAD

**Issue by rockymontana** [IsraelOrtuno/Propertier#34]
Do you have a timeline for the first stable release?

And also - bloody awesome package! I've been looking for packages that solves this problem.

Best of luck!

Jonas

**Comment by IsraelOrtuno** [comment]
@rockymontana thanks. I would say it's currently in Alpha, you can subscribe to this issue #26 so you an follow the current roadmap. Just a few steps away for a first stable.

I am currently looking for people to test it, interested?

**Comment by rockymontana** [comment]
When I have the time - sure!

But to be able to do that (without massively diving into code), I would say that the documentation might need some update...
The ToC doesn't seem to follow the actual content at the moment.

**Comment by rockymontana** [comment]
Well, I peeked into your tests, and those kinda shows how to do it.
