### ISSUE TITLE
Get attributes id with entity attributes

### ISSUE THREAD

**Issue by pinguinjkeke** [IsraelOrtuno/Propertier#39]
How to get attribute id with entity attributes?

**Comment by IsraelOrtuno** [comment]
I guess you want to get an entity with attributes right?

``` php
$company = Company::with('eav')->get();
```

**Comment by pinguinjkeke** [comment]
No. I'm developing administrative part of application and I need to access value id for collection attributes. There are id, content, attribute_id and entity_id in value table. I need that id

**Comment by IsraelOrtuno** [comment]
Can you please explain it more widely? I am sorry but I do not understand.

**Comment by rockymontana** [comment]
You dont really need that because the attributes functions as properties in the model. So you save them by their property names (that is: the model property name === Attribute::whereName($name)).
