### ISSUE TITLE
How to "extend" fillable for storing eav values

### ISSUE THREAD

**Issue by Chalkin** [IsraelOrtuno/Propertier#43]
What is the best way with your package to extend the fillable attribute to let laravel store the EAV values. Currently laravel is filtering out the EAV attributes and values when I try to store a resource.

Is there something integrated in the package to handle that?

**Comment by breaktag** [comment]
I don't believe you need to add anything in your fillable property. I was struggling when setting up but I realised the attribute has to exist before you can use 'setAttribute'. Always use setAttribute before executing your $model->update() method.

**Comment by Chalkin** [comment]
Well, the attribute is already defined in the database table eav_attributes (city, facebook) - but when updating a record the values for the eav attributes are filtered out.

That's the controller update method:

``` php
public function update(Request $request, $id)
    {
        $customer = Customer::findOrFail($id);
        $customer->update($request->all());
        return redirect()->route('customers.index', ['id' => $customer->id]);
    }
```

Thats the model:

``` php
<?php

namespace App;

use \Devio\Eavquent\Eavquent;
use Illuminate\Database\Eloquent\Model;

class Customer extends Model
{
    use Eavquent;

    protected $with = [ 'eav' ];

    protected $fillable = [
        'user_id',
        'name',
    ];
}
```

And that's my test repository: [EAVquent Test/](https://bitbucket.org/Klostermeier/eavquent/)
