### ISSUE TITLE
Delete Attribute Values when Attribute is Destroyed?

### ISSUE THREAD

**Issue by timramseyjr** [IsraelOrtuno/Propertier#46]
I might be missing something, but is there a way to remove all of the attribute values (boolean,datetime,floatnum,integer,text,varchar) when the attribute is destroyed?

`Attribute::destroy($id);`

It removes the attribute as expected(eav_attributes), but all of the values remain in the type tables.

something like a cascade delete on a foreign key attribute_id

But like I said previously, I may be missing a detail where this doesn't make sense, or the feature exists that I am not aware of.

**Comment by IsraelOrtuno** [comment]
This part was not yet implemented :( I am currently working on the package so may have news soon
