### ISSUE TITLE
Doesn't work Lazy Eager Loading

### ISSUE THREAD

**Issue by Feniksss** [IsraelOrtuno/Propertier#47]
Hi.
I try to load a fields by: 
```
$test= Test::where('tests.id', $id)
                ->select('tests.*')->first();
$test->load('eav');

```
And I get an error: 
`Call to undefined relationship [eav] on model [App\Test].`

But if I use the construction 'with' in model: `protected $with = ['eav'];` - It's works correct.
So, what's the problem?
Thanks!

**Comment by IsraelOrtuno** [comment]
Laravel version?

**Comment by Feniksss** [comment]
5.3

**Comment by brenjt** [comment]
I am having the same issue on 5.3. I also do not see any logic in the code to handle 'eav' relationship loading.

**Comment by IsraelOrtuno** [comment]
It's located in the scope class. Probably needs a few changes to work with
5.3. This was tested up to 5.2.

**Comment by brenjt** [comment]
The issue seems to be here: ```$eagerLoads = array_merge($eagerLoads, $model->getAttributeRelations());``` ```getAttributeRelations()``` is returning an empty array when booting. But when called after boot it returns the correct data.

**Comment by brenjt** [comment]
I found the problem for me at-least. It had to do with inheritance. If i was overwriting the newFromBuilder and wanted to load a dynamic class instance for my model then the scopes would never be applied resulting in it never loading those relationships.

I think this could be easily resolved if the ```->load('eav')``` worked correctly. I'll see if I can find a solution.
