### ISSUE TITLE
Reduce queries when saving / updating

### ISSUE THREAD

**Issue by IsraelOrtuno** [IsraelOrtuno/Propertier#5]
Check if there is any way to reduce the number of updates when saving. It is currently performing an update query every saved field.

**Comment by dkulyk** [comment]
Only the changed values will be saved. Multiple insert does not return IDs;
For single values you want to use Eloquent saving;
For all multiple values - one delete and one multiple insert for all values:

``` SQL
delete from `eav_values` where `entity_id` = ? and `property_id` in (?);
insert into `eav_values` (`entity_id`, `property_id`, `value`) values (?, ?, ?), (?, ?, ?), (?, ?, ?);
```

https://github.com/dkulyk/eloquent-eav/blob/master/src/PropertyQuery.php#L242-L287

**Comment by IsraelOrtuno** [comment]
I was working on this yesterday and came up with something very similar :+1:
