### ISSUE TITLE
Cache properties

### ISSUE THREAD

**Issue by IsraelOrtuno** [IsraelOrtuno/Propertier#7]
Caching the properties related to entity will reduce a lot the amount of queries as it is something unlikely to change

**Comment by dkulyk** [comment]
You load entity properties for each entity query?
`select * from`properties`where`entity`= ?` 
Maybe we should get once the properties to all entities. And use the available results?
~= https://github.com/dkulyk/eloquent-eav/blob/master/src/Manager.php

**Comment by IsraelOrtuno** [comment]
Yep.. I am wondering if there is an easy way of injecting some caching here

**Comment by dkulyk** [comment]
If you use the property cache, you have to separate the properties and values in the model.

**Comment by IsraelOrtuno** [comment]
Do not really get that. If the properties are cached, instead of fetching them from database, they will be get from the cache manager, nothing should really change. Just the properties as they are pretty unlikely to change. 

Values will carry on same way.

**Comment by dkulyk** [comment]
Many links have properties with the entity and values to be used once getting the properties for many times.
Many clones of properties - a reduction of performance and memory usage.

**Comment by IsraelOrtuno** [comment]
This is supposed to be used with eager loading when retrieving many entities so queries will be fetched just once. By this point we may assume user should take this into account as it should do at any Eloquent query. This is actually acting as a regular relationship.

**Comment by IsraelOrtuno** [comment]
I had to clone the properties as I could not relate the same property to different entities as when loading the values they would load in all the entities and that is not what we want.

**Comment by IsraelOrtuno** [comment]
Creating objects is cheap, nevertheless. Anyone using this approach should be aware of its flexibility but also performance issues.

**Comment by IsraelOrtuno** [comment]
``` SQL
select * from `companies`
select * from `properties` where `entity` = 'App\Company'
select column_name from information_schema.columns where table_schema = 'homestead' and table_name = 'companies'
select * from `property_values` where `property_values`.`entity_id` in ('1', '2', '3', '4', '5', '21') and `property_values`.`entity_type` = 'App\Company'
```

This are the queries executed for retrieving 7 entities (because there are just those), their properties and values. Just 4 queries. Taking into account we can avoid the call to the `colunm_name` stuff by setting the column names manually, 3 queries I think is not bad at all :)

I have worked pretty hard reducing the amount of queries as much as I could. Just wondering if there is an easy and interesting way of caching properties so we could end up with just 2 queries.

**Comment by dkulyk** [comment]
``` PHP
Client::query()->with('properties')->get();
Client::query()->with('properties')->get();
```

Query 1

``` SQL
select * from `clients`
select * from `properties` where `entity` = 'Client'
select column_name from information_schema.columns where table_schema = 'nas' and table_name = 'clients'
select * from `property_values` where `property_values`.`entity_id` in (1, 2) and `property_values`.`entity_type` = 'Client'
```

Query 2

``` SQL
select * from `clients`
select * from `properties` where `entity` = 'Client'
select * from `property_values` where `property_values`.`entity_id` in (1, 2) and `property_values`.`entity_type` = 'Client'
```

My implementation load properties once for all entities(-1 query for Entity query)
Property is meta. Just eager loading values
Query 1:

``` SQL
select * from `eav_properties`
select * from `clients`
select * from `eav_values` where `property_id` in (3, 4, 5, 7) and `entity_id` in (1, 2)
```

Query 2:

``` SQL
select * from `clients`
select * from `eav_values` where `property_id` in (3, 4, 5, 7) and `entity_id` in (1, 2)
```

**Comment by IsraelOrtuno** [comment]
Ok, we'll see this. By now I would like to have a kind of stable version and keep working improving things like this :)

**Comment by IsraelOrtuno** [comment]
Done
